project:
  type: website
  output-dir: docs

website:
  title: "Noah Manning's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Science Projects
        menu:
        - href: marchmadness.qmd
          text: March Madness
        - href: collegebudgets.qmd
          text: College Sports Budgets
        - href: tweets.qmd
          text: Trump Tweet Analysis
        - href: projectpart3.qmd
          text: High School GPA Analysis
        - href: Project4.qmd
          text: Amazon Hiring Ethics
        - href: projectpart5.qmd
          text: SQL Wrangling
        - href: Project6.qmd
          text: Permutation Testing Presentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


