project:
  type: website
  output-dir: docs

website:
  title: "Noah Manning's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: marchmadness.qmd
        text: March Madness
      - href: collegebudgets.qmd
        text: College Sports Budgets

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
