project:
  type: website
  output-dir: docs

website:
  title: "Noah Manning's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: marchmadness.qmd
        text: March Madness
      - href: collegebudgets.qmd
        text: College Sports Budgets
      - href: tweets.qmd
        text: Project 2 Tweet Analysis
      - href: projectpart3.qmd
        text: Project 3
      - href: Project4.qmd
        text: Project Part 4

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


